# Copyright 2022 Mariyan Dimitrov
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  category:
    default: ""
    description: A category to use for Chuck Norris jokes.
    type: string
